---
- name: Target 1 - Build Servers
  hosts: build_servers
  become: true
  pre_tasks:
    - name: Print the executing user
      ansible.builtin.debug:
        msg: "{{ lookup('env', 'USER') }}"
    - name: Demonstrate custom filter
      ansible.builtin.debug:
        msg: "{{ 'Deploying infrastructure' | make_uppercase }}"
  roles:
    - jenkins_docker

- name: Target 2 - Shared Services
  hosts: shared_services
  become: true
  strategy: free
  roles:
    - common
    - nexus
    - sonarqube
