---
- name: Ensure base packages needed for repo management are present
  ansible.builtin.apt:
    name:
      - openjdk-21-jre-headless
      - firewalld
      - python3-firewall
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - acl
    state: present
    update_cache: true

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
