---
- name: Download Jenkins GPG key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
    dest: /etc/apt/keyrings/jenkins.asc
    mode: "0644"

- name: Add Jenkins apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/jenkins.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    update_cache: true

- name: Install Jenkins
  ansible.builtin.apt:
    name:
      - jenkins
    state: present
