---
- name: Include OS-specific setup tasks
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add jenkins user to docker group
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: true
  notify: Restart jenkins

- name: Configure Docker insecure registry for Nexus Docker connector
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    mode: "0644"
    content: |
      {
        "insecure-registries" : ["{{ groups['shared_services'][0] }}:8082"]
      }
  notify: Restart docker

- name: Create systemd drop-in directory for Jenkins
  ansible.builtin.file:
    path: /etc/systemd/system/jenkins.service.d
    state: directory
    mode: "0755"

- name: Disable Jenkins Setup Wizard and define JCasC path
  ansible.builtin.copy:
    dest: /etc/systemd/system/jenkins.service.d/override.conf
    mode: "0644"
    content: |
      [Service]
      Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dcasc.jenkins.config=/var/lib/jenkins/jenkins.yaml -Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"

- name: Ensure firewalld and docker are enabled and started
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    daemon_reload: true
  loop:
    - firewalld
    - docker

- name: Download Jenkins Plugin Manager
  ansible.builtin.get_url:
    url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.15/jenkins-plugin-manager-2.12.15.jar
    dest: /opt/jenkins-plugin-manager.jar
    mode: "0755"

- name: Install Jenkins Plugins via CLI
  ansible.builtin.command:
    cmd: >
      java -jar /opt/jenkins-plugin-manager.jar
      --war /usr/share/java/jenkins.war
      --plugin-download-directory /var/lib/jenkins/plugins
      --plugins configuration-as-code job-dsl workflow-aggregator git sonar nexus-artifact-uploader slack
  become: true
  become_user: jenkins
  register: plugin_install

- name: Deploy JCasC Configuration
  ansible.builtin.template:
    src: jenkins.yaml.j2
    dest: /var/lib/jenkins/jenkins.yaml
    owner: jenkins
    group: jenkins
    mode: "0644"
  notify: Restart jenkins

- name: Ensure Jenkins is enabled and started
  ansible.builtin.systemd:
    name: jenkins
    enabled: true
    state: started
    daemon_reload: true

- name: Open HTTP and Jenkins ports in firewalld
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - 80/tcp    # HTTP
    - 8080/tcp  # Jenkins UI
    - 8083/tcp  # Production deployment
    - 8084/tcp  # UAT deployment
